### ISSUE TITLE
CakePHP 3.5 support

### ISSUE THREAD

**Issue by infokani** [CakeDC/users#596]

**Comment by steinkel** [comment]
Yeah that makes a lot of sense now it's been released...

**Comment by Tomicapo** [comment]
Hi. any plans on implementing this? May I help in some way?

**Comment by steinkel** [comment]
fixed in develop

**Comment by steinkel** [comment]
we'll be pushing a new version in the following days, please use develop branch for now

**Comment by Tomicapo** [comment]
Can I do that with composer? How?

**Comment by jtraulle** [comment]
@Tomicapo put **dev-develop** as version constraint in composer.json

**Comment by jtraulle** [comment]
@steinkel Still can't upgrade to 3.5 with latest users plugin. See #601 :wink:

**Comment by Tomicapo** [comment]
Thanks @jtraulle I figured it out. It worked well.

**Comment by Oxicode** [comment]
+1

**Comment by steinkel** [comment]
fixed in release 5.2.0, please note we'll remove deprecations and release 6.0.0 that will be compatible with CakePHP ^3.5
